### ISSUE TITLE
datasets: use versionID instead of bookid

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#10]
## Page URL: 

https://mabarber92.github.io/data#alignment-files

### Before:
The file name takes the format of bookid1_bookid2. (On book IDs and the way we name the books in our corpus, see our page on using the corpus.)

### After
The file name takes the format of **versionID1_versionID2**. (On **versionIDs** and the way we name the **files** in our corpus, see our page on using the corpus.)

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Thank you. See updates here: http://127.0.0.1:4000/data/#alignment-files

Let me know if you see any further issues.
