### ISSUE TITLE
reorganize the alignment files explanation?

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#12]
## Page URL: 

https://mabarber92.github.io/data#alignment-files

The order of the explanations does not feel logical. I would first explain what is in those files, and only after that, explain the naming system and the different versions. 

### Before:
If passim identifies text reuse between two books, a file is produced. A separate file is produced for both the **normal** and **aggregated** datasets. The file name takes the format of *bookid1_bookid2*. (On book IDs and the way we name the books in our corpus, see our page on [using the corpus]({{ 'corpus/use#uri-structure' | relative_url }}).) The file recording alignments between Ibn Hisham's *Sira* and al-Tabari's *Taʾrikh* would, therefore be:

Shamela0009783BK1-ara1.completed_Shamela0023833-ara1.completed.csv
{: .notice--primary}

For ease of identifying text pairs, we produce each alignment file in both directions, so:

Shamela0023833-ara1.completed_Shamela0009783BK1-ara1.completed.csv
{: .notice--primary}

Would be a flipped version of the same file.

In each file, each row gives an alignment between the text pair, recording the aligned text (aligned using [Smith-Waterman]({{ '/methods/text-reuse#how-does-passim-work' | relative_url }})), the location of each alignment in the book and some statistics about each alignment. For detailed guidance on the data fields, see our [docs]().

The main difference between the alignment files for **normal** and **aggregated** is that the location of **normal** alignments is given as a milestone, where for **aggregated** a milestone range is provided.

### After

If passim identifies text reuse between two books, a file is produced.  **In each file, each row gives ***data on one aligned passage in*** the text pair, recording the aligned text (aligned using ***the*** [Smith-Waterman]({{ '/methods/text-reuse#how-does-passim-work' | relative_url }}) ***algorithm***), the location of each alignment in ***both*** books and some statistics about each alignment. For detailed guidance on the data fields, see our [docs]().**

The file name takes the format of *bookid1_bookid2*. (On book IDs and the way we name the books in our corpus, see our page on [using the corpus]({{ 'corpus/use#uri-structure' | relative_url }}).) The file recording alignments between Ibn Hisham's *Sira* and al-Tabari's *Taʾrikh* would, therefore be:

Shamela0009783BK1-ara1.completed_Shamela0023833-ara1.completed.csv
{: .notice--primary}

For ease of identifying text pairs, we produce each alignment file in both directions, so:

Shamela0023833-ara1.completed_Shamela0009783BK1-ara1.completed.csv
{: .notice--primary}

**would** be a flipped version of the same file.

**A separate file is produced for both the **normal** and **aggregated** datasets.** The main difference between the alignment files for **normal** and **aggregated** is that the location of **normal** alignments is given as a milestone, where for **aggregated** a milestone range is provided.

## Issue with the website:
*Describe the issue*

## New feature/page
*Describe what you would like adding*

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Thank you this order makes much better sense. 

See the fixes here: https://mabarber92.github.io/data#alignment-files
