### ISSUE TITLE
Mention that passim data is created for every release of the corpus + difference between primary and secondary runs

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#13]
## Page URL: 

https://mabarber92.github.io/data#passim-text-reuse-datasets

### Before:
Passim text reuse datasets

We produce two types of passim dataset: normal and aggregated. 

### After
Passim text reuse datasets

**We run passim on our corpus every time we release a new version of the corpus. For each passim run, we **produce two types of passim dataset: normal and aggregated.

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Thanks. Updates are here: https://mabarber92.github.io/data#passim-text-reuse-datasets 

Let me know if you spot any issues.
