### ISSUE TITLE
pairwise viz explanation: add less technical explanation?

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#14]
## Page URL: 

https://mabarber92.github.io/data/viz

Perhaps it's useful to add a simplified explanation of the visualization that doesn't include terms like x axis, milestones, etc. Something like: 

"The visualization represents each of the two works as a 300-words wide scroll of which the top is on the left and the bottom on the right. Passages that are common to both works are highlighted in red. The yellow lines connect the common passages between the books."

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
See updates here: https://mabarber92.github.io/data/viz

Let me know if this is all ok.
