### ISSUE TITLE
"When does KITAB run passim?" Add that passim runs are linked to specific corpus release

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#18]
## Page URL: 

https://mabarber92.github.io/methods/text-reuse#when-does-kitab-run-passim 

### Before:
Passim is run at least twice every year to account for corpus changes. We do not run it more regularly because the preparation of the corpus and subsequent analysis of the data produced by passim is very time consuming. It is important for us that the corpus is prepared appropriately and that the data and subsequent analysis is checked thoroughly, to guard against potential errors.

### After
Passim is run at least twice every year to account for corpus changes. We do not run it more regularly because the preparation of the corpus and subsequent analysis of the data produced by passim is very time consuming. It is important for us that the corpus is prepared appropriately and that the data and subsequent analysis is checked thoroughly, to guard against potential errors. **Each time passim is run, the corpus as it is at that point is released on Zenodo, so that the text reuse data can always be linked back to the state the texts were in when passim was run.**

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Thank you, I've added your suggestions here: https://mabarber92.github.io/methods/text-reuse#when-does-kitab-run-passim

I also added a link to Lorenz's helpful explanation of the difference between the stable and evolving corpus.
