### ISSUE TITLE
home page: 'search the OpenITI corpus'

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#3]
## Page URL: 

https://mabarber92.github.io/

## Suggested content change

* change the title to "Find a book in the OpenITI corpus" ? (search suggests you can do full-text search)
* move this block up, above the Twitter feed?

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Layout changes](https://trello.com/c/Wg2wbqLv/28-layout-changes)

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
I've done both, which I'm hoping is a little clearer: https://mabarber92.github.io/

Now I've flipped them around I do think this arrangement is better.
