### ISSUE TITLE
Home page: "Read more blogs"

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#4]
## Page URL: 

https://mabarber92.github.io/

## Issue with the website:
The "Read other blogs" button leads to one other blog. It would be more useful if this button linked to a list of all blogs that can be filtered on multiple subjects (basically, https://mabarber92.github.io/blogs)

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Liquid fixes](https://trello.com/c/DQ7licv9/29-liquid-fixes)

**Comment by mabarber92** [comment]
Thanks for spotting this. It should have linked to the blogs page. 

See fix here: https://mabarber92.github.io/
