### ISSUE TITLE
Message from the Corpus team: mention relationship with OpenITI

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#5]
## Page URL: 

https://mabarber92.github.io/corpus/

### Before:
KITAB corpus is KITAB’s constantly evolving corpus of machine-readable (mostly) premodern Arabic texts and metadata files.

### After
KITAB corpus is KITAB’s constantly evolving corpus of machine-readable (mostly) premodern Arabic texts and metadata files. It is  part of the larger OpenITI corpus.

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Updates are now here: https://mabarber92.github.io/corpus/

@Lrnzmtths could you confirm your happy with this (as technically it's your message)
