### ISSUE TITLE
Corpus and data message

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#7]
## Page URL: 

https://mabarber92.github.io/corpus/

## Issue with the website:
The landing page for this section talks only about the Corpus, not about Data and Corpus. 

Perhaps we need to re-organize the structure of this section, so that one lands on a very short message explaining that the project is based on a corpus and that we produce a lot of data, and then have separate sections on Corpus and on Data. 

# Before:

CORPUS AND DATA
Message from the team
About the corpus
Using the corpus
mARkdown
OCR
Corpus releases
Read more

DATASETS
About our data
About our Vizualisations
Use Our Applications
Read more

#After: 

**CORPUS AND DATA**
**Message from the team**

CORPUS
Message from the team
About the corpus
Using the corpus
mARkdown
OCR
Corpus releases
Read more

DATASETS
About our data
About our Vizualisations
Use Our Applications
Read more

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Nav updates](https://trello.com/c/wWWHo1cG/26-nav-updates)

**Comment by mabarber92** [comment]
Updated the nav and created a new page with the introduction you suggest, here: https://mabarber92.github.io/corpus-and-data

The text there is very provisional and I'm open to suggestions.
