### ISSUE TITLE
Passim text reuse datasets: add link to explanation about passim

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#8]
## Page URL: 

https://mabarber92.github.io/data#passim-text-reuse-datasets

### Before:
We produce two types of passim dataset: normal and aggregated. 

### After
A major part of our research is based on text reuse detection using the [passim algorithm](https://mabarber92.github.io/methods/text-reuse#introducing-passim). We produce two types of passim dataset: normal and aggregated.

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
See updates here: https://mabarber92.github.io/data#passim-text-reuse-datasets

Let me know if  you see any further issues.
