### ISSUE TITLE
Passim text reuse datasets

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#9]
## Page URL: 

https://mabarber92.github.io/data#passim-text-reuse-datasets

### Before:
The normal dataset uses passim alignments based on the milestones (the logical chunks that we use to run passim). In this dataset large alignments might be split across multiple milestones. The aggregated dataset takes large alignments the cross milestones and brings them together into one alignment.

### After
The normal dataset uses passim alignments based on the milestones (**the 300-word chunks into which we divide texts before running passim**). In this dataset large alignments might be split across multiple milestones; **this dataset is especially useful for [book-to-book visualization](https://mabarber92.github.io/data/viz) of text reuse.** The aggregated dataset takes large alignments **that** cross milestones and brings them together into one alignment; **this dataset is particularly useful for close reading**.

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Thank you for these suggestions. See the edits here: http://127.0.0.1:4000/data/#passim-text-reuse-datasets

Let me know if you see any issues.
